### ISSUE TITLE
idb performSave failed:  TypeError: Cannot assign to read only property 'data' of object '#<LokiEventEmitter>'

### ISSUE THREAD

**Issue by shadrackmwangi** [Nozbe/WatermelonDB#1709]
This error is intermittently thrown in my applications dashboard - React app with lokijs
```js
consoleObservable.js:30 idb performSave failed:  TypeError: Cannot assign to read only property 'data' of object '#<LokiEventEmitter>'
```
Followed by an infinite loop of 
```js
consoleObservable.js:30 idb performSave failed:  TypeError: Cannot read properties of null (reading 'forEach')
    at populateChunk (incremental-indexeddb-adapter.js:519:1)
    at Array.forEach (<anonymous>)
    at Collection.lokiDeserializeCollectionChunks [as getData] (incremental-indexeddb-adapter.js:512:1)
    at Collection.get [as data] (lokijs.wmelon.js:1314:1)
    at Collection.ensureId (lokijs.wmelon.js:3397:1)
    at IncrementalIndexedDBAdapter._getChunk (incremental-indexeddb-adapter.js:76:1)
    at prepareChunk (incremental-indexeddb-adapter.js:316:1)
    at prepareCollection (incremental-indexeddb-adapter.js:337:1)
    at Array.forEach (<anonymous>)
    at IncrementalIndexedDBAdapter._putInChunks (incremental-indexeddb-adapter.js:370:1)
```
And
```js
lokijs.wmelon.js:1767 Uncaught RangeError: Invalid array length
    at Array.concat (<anonymous>)
    at lokijs.wmelon.js:1767:1
    at Array.forEach (<anonymous>)
    at exportDatabaseCallback (lokijs.wmelon.js:1764:1)
    at finish (incremental-indexeddb-adapter.js:174:1)
    at tx.onerror (incremental-indexeddb-adapter.js:196:1)
```

I use watermelon db to manage the state of the forms and ensure no data loss in case of network issues or reloading. The react app can be used to manage the state of multiple users by an admin, instead of using a single db for all the users, I have a unique `dbName` for each user (basically `{their_id.db}`) to minimize synchronization issues. The backend is not primed for the sync API so I have implemented syncing internally in this manner
- Any action a user takes such as creating a new form, submitting a form
- An API call to the respective API is made, and with the result I update the local indexed db data.

However, this series of issues keep coming up, sometimes meaning that the user cannot perform any actions on the db, and in extreme cases where we depend on local changes to be persisted, end up losing their data.

I could really appreciate any help with this.

**Comment by sheldonbaker** [comment]
@shadrackmwangi What was the solution for this?

**Comment by radex** [comment]
this has been fixed in recent pre-release
