### ISSUE TITLE
Any plans to support 0.76+

### ISSUE THREAD

**Issue by enahum** [Nozbe/WatermelonDB#1851]
It’s been a while since version 0.74 introduced some breaking changes (I managed to find a workaround, though). However, with version 0.76 now available, it appears that there’s no way to make it work with jsi enabled.

Unless someone has a workaround, I’m curious to know if this is being considered for a future update.

**Comment by NikolaGrgic** [comment]
I doubt it.

I've personally tried to use this library numerous times and always run into errors that are highly difficult to debug, especially on the newer architecture. I've had multiple sessions that go on for several hair-pulling hours that that end up being resolved by resetting the React Native cache and deleting and reinstalling the app. This is simply a **poor developer experience** and there's no way around it. The most damning part is when you realize that there are _no viable alternatives for WatermelonDB on React Native_.

I considered contributing to this project to help resolve some issues, but I cannot find the time due to work constraints, and I'm concerned that, with how much of a mess this project has become, I simply won't be able to contribute effectively. For example, there are 23 PRs still open (**some as far back as 2020**) and issues that are flat-out being ignored, like this particular one.

I imagine the maintainers don't want to give up control of the repo, but they seemingly also lack the time to be able to effectively maintain and update this library. To clarify, **I do not wish to put them down in any way** - I'm simply calling it as I see it. I understand that people get busy (like myself) and they can't always contribute to open-source. Such is life, and **I do not blame them**.

I think, above else, that there needs to be a drastic way in which this project is maintained, especially when offline-first apps are a priority for so many people developing with React Native. I love the React Native community so much, and I certainly don't want to give any more reasons for people to use Flutter instead! 😅

As a result of everything, I wanted to put it out there that the minute I get a chance, I'm working on a full replacement for WatermelonDB that features:

- New React Native Architecture Support
- Full TypeScript Support
- Modern Practices + Simpler API (React Hooks, etc.)
- Better Error Handling
- Better Documentation

Let me know if you or someone else is interested in developing this.

**Comment by lucaswitch** [comment]
> It’s been a while since version 0.74 introduced some breaking changes (I managed to find a workaround, though). However, with version 0.76 now available, it appears that there’s no way to make it work with jsi enabled.
> 
> Unless someone has a workaround, I’m curious to know if this is being considered for a future update.

The jsi mode is not needed anymore cause we have turbo modules stable now. In that way all library events and calls needs to be typesafe and be ported through codegen.

Also one thing that we have to keep in mind is to keep backwards support(the old bridge) until they launch a version that meta actually removes it completely.

One thing that broke WatermelonDb is actually not related with it at all.

The latest react-native babel preset does not work well with "babel-decorators plugin" which we depend heavily to addressing models.
Thats something that is already is fixed on new version 0.76.2, see https://github.com/facebook/hermes/issues/1549.

For people having this issue the workaround is renaming all the models to .ts and enabling typescript experimental decorators support.

**Comment by angelo-hub** [comment]
sorry posted to early glad you guys are on top of this @lucaswitch

**Comment by prathameshmm02** [comment]
This https://github.com/Nozbe/WatermelonDB/pull/1854 works on RN-0.76. But, if you are using Expo, watermelon will need to be manually linked, due to Expo's new [autolinking](https://docs.expo.dev/modules/autolinking/), as watermelon-db's android and ios folders are located in native folder which Expo's autolinking doesn't seem to be picking up for autolinking.

**Comment by caiopratali** [comment]
> This #1854 works on RN-0.76. But, if you are using Expo, watermelon will need to be manually linked, due to Expo's new [autolinking](https://docs.expo.dev/modules/autolinking/), as watermelon-db's android and ios folders are located in native folder which Expo's autolinking doesn't seem to be picking up for autolinking.

Tnks!!

To use watermelondb with react native 0.76 and expo 0.52 set EXPO_USE_COMMUNITY_AUTOLINKING=1 and add @react-native-community/cli

**Comment by radex** [comment]
Hi everyone,

0.28.0-1 now works on RN 0.74+ (Android/JSI). Note a small breaking change is needed for this -- see this comment for details: https://github.com/Nozbe/WatermelonDB/issues/1769#issuecomment-2507899744

Please let me know if this works for you on 0.75/0.76, and if not, what issues you're encountering.

— Radek

**Comment by CodeWithBlaze** [comment]
will this also work on the 0.76+ new arch and jsi enabled ? because i am getting strange errors like this 
` Caused by: java.lang.NullPointerException
                                                                                                    	at com.facebook.react.runtime.BridgelessCatalystInstance.getReactQueueConfiguration(BridgelessCatalystInstance.kt:116)
                                                                                                    	at com.nozbe.watermelondb.WMDatabaseBridge.invalidate(WMDatabaseBridge.java:251)
                                                                                                    	at com.facebook.react.internal.turbomodule.core.TurboModuleManager.invalidate(TurboModuleManager.java:417)`
                                                                                                    	
when i reload the app

@radex can you confirm this please. Using pre-release version 0.28.0-1

**Comment by Dallas62** [comment]
@radex Works well on 0.76, the small change mentioned is not required. Already imported by Codegen as far as I see (new arch at least).

**Comment by ALTHGA** [comment]
> will this also work on the 0.76+ new arch and jsi enabled ? because i am getting strange errors like this ` Caused by: java.lang.NullPointerException at com.facebook.react.runtime.BridgelessCatalystInstance.getReactQueueConfiguration(BridgelessCatalystInstance.kt:116) at com.nozbe.watermelondb.WMDatabaseBridge.invalidate(WMDatabaseBridge.java:251) at com.facebook.react.internal.turbomodule.core.TurboModuleManager.invalidate(TurboModuleManager.java:417)`
> 
> when i reload the app
> 
> @radex can you confirm this please. Using pre-release version 0.28.0-1

same problem!

**Comment by mobtex** [comment]
> will this also work on the 0.76+ new arch and jsi enabled ? because i am getting strange errors like this ` Caused by: java.lang.NullPointerException at com.facebook.react.runtime.BridgelessCatalystInstance.getReactQueueConfiguration(BridgelessCatalystInstance.kt:116) at com.nozbe.watermelondb.WMDatabaseBridge.invalidate(WMDatabaseBridge.java:251) at com.facebook.react.internal.turbomodule.core.TurboModuleManager.invalidate(TurboModuleManager.java:417)`
> 
> when i reload the app
> 
> @radex can you confirm this please. Using pre-release version 0.28.0-1

same problem 2!

**Comment by deeeed** [comment]
Same issue here.

**Comment by rohankm** [comment]
any updates on this?

**Comment by MatheusHCP** [comment]
https://github.com/Nozbe/WatermelonDB/issues/1769#issuecomment-2588738330

with this comment i running Watermelon DB in Expo SDK 52 and RN 0.76 with new arch enabled.

**Comment by rohankm** [comment]
> [#1769 (comment)](https://github.com/Nozbe/WatermelonDB/issues/1769#issuecomment-2588738330)
> 
> with this comment i running Watermelon DB in Expo SDK 52 and RN 0.76 with new arch enabled.

with JSI?

**Comment by LovesWorking** [comment]
> I doubt it.
> 
> I've personally tried to use this library numerous times and always run into errors that are highly difficult to debug, especially on the newer architecture. I've had multiple sessions that go on for several hair-pulling hours that that end up being resolved by resetting the React Native cache and deleting and reinstalling the app. This is simply a **poor developer experience** and there's no way around it. The most damning part is when you realize that there are _no viable alternatives for WatermelonDB on React Native_.
> 
> I considered contributing to this project to help resolve some issues, but I cannot find the time due to work constraints, and I'm concerned that, with how much of a mess this project has become, I simply won't be able to contribute effectively. For example, there are 23 PRs still open (**some as far back as 2020**) and issues that are flat-out being ignored, like this particular one.
> 
> I imagine the maintainers don't want to give up control of the repo, but they seemingly also lack the time to be able to effectively maintain and update this library. To clarify, **I do not wish to put them down in any way** - I'm simply calling it as I see it. I understand that people get busy (like myself) and they can't always contribute to open-source. Such is life, and **I do not blame them**.
> 
> I think, above else, that there needs to be a drastic way in which this project is maintained, especially when offline-first apps are a priority for so many people developing with React Native. I love the React Native community so much, and I certainly don't want to give any more reasons for people to use Flutter instead! 😅
> 
> As a result of everything, I wanted to put it out there that the minute I get a chance, I'm working on a full replacement for WatermelonDB that features:
> 
> * New React Native Architecture Support
> * Full TypeScript Support
> * Modern Practices + Simpler API (React Hooks, etc.)
> * Better Error Handling
> * Better Documentation
> 
> Let me know if you or someone else is interested in developing this.

I would love to work with you on this as well.

**Comment by fillipeags** [comment]
Any plans on this being published as a new version rather than a pre-release install any time soon ?

**Comment by ghost** [comment]
any news about this?, I'm using this great plugin because of its great sync capabilities without third part plugins, and now I required to migrate do react native 79 with new arch enabled cant use it anymore

**Comment by fillipeags** [comment]
I'm on the same situation @juanpvmsnz . It would be really helpful if any of the core maintainers could reply here for us to have expectations on a new release or plan a migration to another library in cause it could become unsustainable to keep using it since react native is approaching the "new era" without old arch support
