### ISSUE TITLE
Schema migration issue - multiple tabs

### ISSUE THREAD

**Issue by gligorevic** [Nozbe/WatermelonDB#1865]
When multiple tabs are open and a schema version update is triggered (with migrations enabled), only one tab migrates successfully. The other tabs enter an infinite loop, resulting in the following error message:

idb performSave failed:  TypeError: Cannot read properties of null (reading 'forEach')
    at incremental-indexeddb-adapter.js:519:21
    at Array.forEach (<anonymous>)
    at k.d [as getData] (incremental-indexeddb-adapter.js:512:24)
    at k.get [as data] (lokijs.wmelon.js:1314:31)
    at k.ensureId (lokijs.wmelon.js:3397:23)
    at t._getChunk (incremental-indexeddb-adapter.js:76:18)
    at f (incremental-indexeddb-adapter.js:316:32)
    at u (incremental-indexeddb-adapter.js:337:13)
    at Array.forEach (<anonymous>)
    at t._putInChunks (incremental-indexeddb-adapter.js:370:24)

**Comment by kokusGr** [comment]
I have a partial fix in this PR: https://github.com/Nozbe/WatermelonDB/pull/1921. It doesn't address only one tab migrating, but at least the app shouldn't go into an infinite loop and still work correctly.
