### ISSUE TITLE
Web installation: webpack-dev-server crashes on last step from docs (LokiJS adapter)

### ISSUE THREAD

**Issue by alanbuchanan** [Nozbe/WatermelonDB#54]
### Description of Issue
I am using [these docs](https://github.com/Nozbe/WatermelonDB/blob/master/docs/Installation.md) to set up a WatermelonDV project. I'm using [this boilerplate](https://github.com/KleoPetroff/react-webpack-boilerplate). Installation is all fine up to the last step where I need to `import LokiJSAdapter from '@nozbe/watermelondb/adapters/lokijs'`. 

### Error message in console
```
> $ yarn start                                                                                                                                                                           [±master ●●]
yarn run v1.5.1
$ webpack-dev-server
(node:78559) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/rorysmith/WebstormProjects/react-webpack-boilerplate/build
ℹ ｢wds｣: 404s will fallback to /index.html
/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/worker-loader/dist/index.js:121
      worker.factory = (0, _workers2.default)(worker.file, compilation.assets[worker.file].source(), options);
                                                                                           ^

TypeError: Cannot read property 'source' of undefined
    at worker.compiler.runAsChild (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/worker-loader/dist/index.js:121:92)
    at compile (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compiler.js:296:11)
    at hooks.afterCompile.callAsync.err (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compilation.js:1295:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compilation.js:1286:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compilation.js:1281:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c webpack-dev-server
Directory: /Users/rorysmith/WebstormProjects/react-webpack-boilerplate
```
### Expected Behaviour
Presumably, this package should be available as part of `@nozbe/watermelondb/adapters`

### Current Behaviour
webpack-dev-server crashes

### Possible Solution
When I `yarn add lokijs`, the build runs successfully, albeit with the following warning:
```
    WARNING in ../node_modules/lokijs/src/lokijs.js
    Module not found: Error: Can't resolve 'fs' in '/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/lokijs/src'
     @ ../node_modules/lokijs/src/lokijs.js
     @ ../node_modules/@nozbe/watermelondb/esm/adapters/lokijs/worker/executor.js
     @ ../node_modules/@nozbe/watermelondb/esm/adapters/lokijs/worker/lokiWorker.js
     @ ../node_modules/@nozbe/watermelondb/esm/adapters/lokijs/worker/index.worker.js

```

### Context (Environment)
```
"react": "16.5.2",
"webpack": "4.19.1",
"@nozbe/watermelondb": "^0.6.1",
```

How can I fix this properly?

**Comment by ikhsanalatsary** [comment]
maybe you forgot to install loki `yarn add lokijs`

**Comment by radex** [comment]
```
/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/worker-loader/dist/index.js:121
      worker.factory = (0, _workers2.default)(worker.file, compilation.assets[worker.file].source(), options);
                                                                                           ^

TypeError: Cannot read property 'source' of undefined
    at worker.compiler.runAsChild (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/worker-loader/dist/index.js:121:92)
    at compile (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compiler.js:296:11)
    at hooks.afterCompile.callAsync.err (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compilation.js:1295:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compilation.js:1286:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/webpack/lib/Compilation.js:1281:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
```

that seems strange — looks like you have web pack `worker-loader` (you did install and configure it yourself on top of the boilerplate, correct?) set up, but it fails. I have no idea why that would happen to be honest.

```
Possible Solution

When I yarn add lokijs, the build runs successfully, albeit with the following warning:

    WARNING in ../node_modules/lokijs/src/lokijs.js
    Module not found: Error: Can't resolve 'fs' in '/Users/rorysmith/WebstormProjects/react-webpack-boilerplate/node_modules/lokijs/src'
     @ ../node_modules/lokijs/src/lokijs.js
     @ ../node_modules/@nozbe/watermelondb/esm/adapters/lokijs/worker/executor.js
     @ ../node_modules/@nozbe/watermelondb/esm/adapters/lokijs/worker/lokiWorker.js
     @ ../node_modules/@nozbe/watermelondb/esm/adapters/lokijs/worker/index.worker.js

```

So let me get this straight — you're saying the app works correctly when you `yarn add lokijs` (that is a necessary step), but _webpack_ shows a warning? Not the app console log, just web pack? And the app works?

If so, this is a strange, but minor issue. LokiJS won't be loading `fs` in WatermelonDB, unless we have a bug somewhere.

**Comment by radex** [comment]
Hmm, just realized, the installation guide https://github.com/Nozbe/WatermelonDB/blob/master/docs/Installation.md doesn't say you have to `yarn add lokijs` — if you get your app to run successfully, would you mind updating the guide? You can send a quick pull request via web browser

**Comment by radex** [comment]
@alanbuchanan did you get to take a look at this? did you get this problem fixed or did you end up giving up?

**Comment by alanbuchanan** [comment]
@radex sorry for the delay. I saw the lokijs instruction has been added to the readme by now anyway. I had trouble setting up a project due to other separate problems I encountered but I will create new issue(s) for these.
