### ISSUE TITLE
Using with Svelte?

### ISSUE THREAD

**Issue by frederikhors** [Nozbe/WatermelonDB#819]
It's the first time I come here.

I'm a [Svelte 3](https://svelte.dev) happy user.

Do you know if there will ever be a way to use this amazing project with Svelte?

Is it React.js only?

**Comment by radex** [comment]
No, it's not React.js only. There's no React-specific logic in the core, but you'll probably need some glue code similar to our withObservables. Look at this thread: https://github.com/Nozbe/WatermelonDB/issues/765

**Comment by frederikhors** [comment]
I'm tring it right now with a new https://github.com/sveltejs/template app.

I'm using this code:

```js
import { Database } from '@nozbe/watermelondb'
import LokiJSAdapter from '@nozbe/watermelondb/adapters/lokijs'

import schema from './schema'
import Post from 'model/Post'
import Comment from 'model/Comment'

const adapter = new LokiJSAdapter({
  schema,
  useWebWorker: false,
  useIncrementalIndexedDB: true
})

export const database = new Database({
  adapter,
  modelClasses: [Post, Comment],
  actionsEnabled: true
})
```

the very first error when I'm just importing `database` is:

`Uncaught (in promise) TypeError: Failed to resolve module specifier "fs". Relative references must start with either "/", "./", or "../".`

in browser's console.

What can it be?

**Comment by frederikhors** [comment]
So far I can say that I have managed to make it work. Even observables (which in Svelte are very easy to use: https://svelte.dev/docs#Store_contract).

Now the problem is with the declaration of the fields: decorators are creating problems for the bundler (Rollup).

Is there any way to avoid them for now, @radex?

**Comment by frederikhors** [comment]
As soon as I have something stable I will push a test project so it will also pass your sifting and we can maybe officially support Svelte! : D

**Comment by radex** [comment]
> Now the problem is with the declaration of the fields: decorators are creating problems for the bundler (Rollup).
> Is there any way to avoid them for now, @radex?

You can avoid decorators, but it's not been designed for it, so the result isn't pretty. Just take a look at what Watermelon decorators do, they're really simple: https://github.com/Nozbe/WatermelonDB/tree/master/src/decorators

**Comment by frederikhors** [comment]
Thanks. I'm trying with Typescript now. I'll let you know in a few moments.

**Comment by frederikhors** [comment]
It's working with Typescript. I'll update this issue.

**Comment by fachrihawari** [comment]
@frederikhors I love svelte, and wanna made something with svelte+watermelondb, mind to share how you made it works? thanks in advanced

**Comment by niklasgrewe** [comment]
@frederikhors i am also interesting in this topic. Could you explain and show some code snippets, how you made it works? Does it also works with vite.js (the new bundler for sveltekit) ?

**Comment by hangtwenty** [comment]
I tried this out but I haven't gotten it working, at least not with decorators. (I haven't tried without decorators yet, but tomorrow I'll try that)

In my case it's coming down to `_this` vs `this`, after babel's transformed classes into functions.

```
index.js:45 Diagnostic error: Diagnostic error: Cannot run actions because driver is not set up
    at diagnosticError (http://driftcatcher.local:33440/~@/@@/dist/build/@hot/node_modules/.pnpm/@nozbe+watermelondb@0.23.0/node_modules/@nozbe/watermelondb/utils/common/diagnosticError/index.js:27:21)
    at logError (http://driftcatcher.local:33440/~@/@@/dist/build/@hot/node_modules/.pnpm/@nozbe+watermelondb@0.23.0/node_modules/@nozbe/watermelondb/utils/common/logError/index.js:31:50)
    at DatabaseBridge._onError (http://driftcatcher.local:33440/~@/@@/dist/build/@hot/node_modules/.pnpm/@nozbe+watermelondb@0.23.0/node_modules/@nozbe/watermelondb/adapters/lokijs/worker/DatabaseBridge.js:181:33)
    at DatabaseBridge.executeNext (http://driftcatcher.local:33440/~@/@@/dist/build/@hot/node_modules/.pnpm/@nozbe+watermelondb@0.23.0/node_modules/@nozbe/watermelondb/adapters/lokijs/worker/DatabaseBridge.js:79:18)
    at DatabaseBridge.workerContext.onmessage (http://drift.local:33440/~@/@@/dist/build/@hot/node_modules/.pnpm/@nozbe+watermelondb@0.23.0/node_modules/@nozbe/watermelondb/adapters/lokijs/worker/DatabaseBridge.js:50:21)
```

<details>
<summary>DatabaseBridge.js - after the constructor, it starts referring to this instead of _this</summary>

```javascript
"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

exports.__esModule = true;
exports.default = void 0;

var _toConsumableArray2 = _interopRequireDefault(require("@babel/runtime/helpers/toConsumableArray"));

var _logError = _interopRequireDefault(require("../../../utils/common/logError"));

var _invariant = _interopRequireDefault(require("../../../utils/common/invariant"));

var _DatabaseDriver = _interopRequireDefault(require("./DatabaseDriver"));

// don't import whole `utils` to keep worker size small
var DatabaseBridge = /*#__PURE__*/function () {
  function DatabaseBridge(workerContext) {
    var _this = this;

    this.queue = [];
    this._actionsExecuting = 0;
    this.workerContext = workerContext;

    this.workerContext.onmessage = function (e) {
      var action = e.data; // enqueue action

      _this.queue.push(action);

      if (1 === _this.queue.length) {
        _this.executeNext();
      }
    };
  }

  var _proto = DatabaseBridge.prototype;

  _proto.executeNext = function executeNext() {
    var action = this.queue[0];

    try {
      (0, _invariant.default)(0 === this._actionsExecuting, 'worker should not have ongoing actions'); // sanity check

      this._actionsExecuting += 1;
      var {
        type: type,
        payload: payload
      } = action;

      if ('setUp' === type || 'unsafeResetDatabase' === type) {
        this.processActionAsync(action);
      } else {
        var response = this._driverAction(type).apply(void 0, (0, _toConsumableArray2.default)(payload));

        this.onActionDone(action, {
          value: response
        });
      }
    } catch (error) {
      this._onError(action, error);
    }
  };

  _proto.processActionAsync = function processActionAsync(action) {
    return new Promise(function ($return, $error) {
      var type, payload, options, driver, response;

      var $Try_2_Post = function () {
        try {
          return $return();
        } catch ($boundEx) {
          return $error($boundEx);
        }
      };

      var $Try_2_Catch = function (error) {
        try {
          this._onError(action, error);

          return $Try_2_Post();
        } catch ($boundEx) {
          return $error($boundEx);
        }
      }.bind(this);

      try {
        ({
          type: type,
          payload: payload
        } = action);

        if ('setUp' === type) {
          // app just launched, set up driver with options sent
          (0, _invariant.default)(!this.driver, "Loki driver already set up - cannot set up again");
          [options] = payload;
          driver = new _DatabaseDriver.default(options);
          return Promise.resolve(driver.setUp()).then(function () {
            try {
              this.driver = driver;
              this.onActionDone(action, {
                value: null
              });
              return $If_4.call(this);
            } catch ($boundEx) {
              return $Try_2_Catch($boundEx);
            }
          }.bind(this), $Try_2_Catch);
        } else {
          return Promise.resolve(this._driverAction(type).apply(void 0, (0, _toConsumableArray2.default)(payload))).then(function ($await_6) {
            try {
              response = $await_6;
              this.onActionDone(action, {
                value: response
              });
              return $If_4.call(this);
            } catch ($boundEx) {
              return $Try_2_Catch($boundEx);
            }
          }.bind(this), $Try_2_Catch);
        }

        function $If_4() {
          return $Try_2_Post();
        }
      } catch (error) {
        $Try_2_Catch(error)
      }
    }.bind(this));
  };

  _proto.onActionDone = function onActionDone(action, result) {
    (0, _invariant.default)(1 === this._actionsExecuting, 'worker should be executing 1 action'); // sanity check

    this._actionsExecuting = 0;
    this.queue.shift();

    try {
      var response = {
        id: action.id,
        result: result,
        cloneMethod: action.returnCloneMethod
      };
      this.workerContext.postMessage(response);
    } catch (error) {
      (0, _logError.default)(error);
    }

    if (this.queue.length) {
      this.executeNext();
    }
  };

  _proto._driverAction = function _driverAction(type) {
    (0, _invariant.default)(this.driver, "Cannot run actions because driver is not set up");
    var action = this.driver[type].bind(this.driver);
    (0, _invariant.default)(action, "Unknown worker action ".concat(type));
    return action;
  };

  _proto._onError = function _onError(action, error) {
    // Main process only receives error message (when using web workers) — this logError is to retain call stack
    (0, _logError.default)(error);
    this.onActionDone(action, {
      error: error
    });
  };

  return DatabaseBridge;
}();

exports.default = DatabaseBridge;
```

**Comment by hangtwenty** [comment]
I got something working or partially working, but it took some workarounds I haven't tried before on other rollup projects. Hopefully it keeps working 🤞 and if it does, I'll try to share what worked

**Comment by trenta3** [comment]
Hi @hangtwenty ! I'm also interested in building something with WatermelonDB and Svelte, do you have a public sample repository that I can look at?
Is it worth it, in your opinion, to make the two of them cooperate?

**Comment by maietta** [comment]
I'm interested too!

**Comment by jgod** [comment]
> I got something working or partially working, but it took some workarounds I haven't tried before on other rollup projects. (There's definitely some "duct tape.") Hopefully it keeps working 🤞 and if it does, I'll try to share what worked

How is it going?

**Comment by alfrednerstu** [comment]
Anyone got a template for WatermelonDB and Svelte Kit integration now in 2023?

**Comment by bluepuma77** [comment]
Any template for Svelte(Kit) available in 2024? It's gonna be really interesting with upcoming Svelte 5 runes 😄
