### ISSUE TITLE
java.lang.RuntimeException: Could not invoke DatabaseBridge.query

### ISSUE THREAD

**Issue by omidshafai** [Nozbe/WatermelonDB#852]
When runnig project is android api level 16, I get this error:

java.lang.RuntimeException: Could not invoke DatabaseBridge.query
   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
   at android.os.Handler.handleCallback(Handler.java:615)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
   at android.os.Looper.loop(Looper.java:137)
   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
   at java.lang.Thread.run(Thread.java:856)
 Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)

**Comment by omidshafai** [comment]
I still have this problem in Android level 16:

![image](https://user-images.githubusercontent.com/40908579/98898045-002aea80-24c2-11eb-9b9e-0680cf9d499c.png)

**Comment by hasina-riccardo** [comment]
Hi, did you find a solution for this issue? I'm facing to the same problem.

**Comment by omidshafai** [comment]
> Hi, did you find a solution for this issue? I'm facing to the same problem.

No solution, I migrated to RealmDB :(
