### ISSUE TITLE
Unhandled Promise Rejection if column doesn't exist

### ISSUE THREAD

**Issue by bsr203** [Nozbe/WatermelonDB#93]
Hi,

I am getting an unhandled exception error.

It is because I renamed the field, and may solve by recreating or changing the version. But like to know where I can handle similar error in the future. Can you please give an idea which API call is resulting this error.

```
Possible Unhandled Promise Rejection (id: 0):

Exception has occurred: Error
Error: table positions has no column named lat (code 1 SQLITE_ERROR): , while compiling: insert into positions ("id", "_status", "_changed", "last_modified", "lat", "lng") values (?, ?, ?, ?, ?, ?)
    at createErrorFromErrorData (/Users/bsr/myapp/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:146:32)
    at /Users/bsr/myapp/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:95:31
    at MessageQueue.__invokeCallback (/Users/bsr/myapp/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:397:13)
    at /Users/bsr/myapp/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:127:12
    at MessageQueue.__guard (/Users/bsr/myapp/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:9)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (/Users/bsr/myapp/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:126:10)
    at /Users/bsr/myapp/.vscode/.react/debuggerWorker.js:131:58
    at process.<anonymous> (/Users/bsr/myapp/.vscode/.react/debuggerWorker.js:40:9)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)

```

**Comment by radex** [comment]
you need to have a column in the schema. currently you have to change the schema version to reset the database (to add it). documentation for migrations is coming soon

**Comment by bsr203** [comment]
thanks. I was mainly asking whether I can do exception handling (try catch / ...)  somewhere so I can log it or take appropriate action. Hope it is part of migration
